### PR TITLE
Update Package

### LINKED ISSUE #4: Fresh install: pnpm build results in error
Brand new fresh install.

I go to https://github.com/zynth17/vitailse and click "Use this Template" 

And create a new repo from this template.

Git clone my new repo to local.

Run `pnpm i`.

Run `pnpm dev`, works fine! 👍

Run `pnpm build`, results in error. First appears fine: 

But finishes with error

### PR DESCRIPTION
**Pull request by zynth17**
Updating available update package 
removing workbox-window to fix #4

### CODE REVIEW

**Comment by jjaimealeman** [comment]
@zynth17 
I know you're still working on this, thanks for that!

I tried again and it still fails screenshot

Installed workbox, ran build, fails.

Installed workbox-window, ran build, fails.

hmm ...

**Comment by zynth17** [comment]
remove the workbox depedencies from package.json

**Comment by zynth17** [comment]
> @zynth17 
> 
> I know you're still working on this, thanks for that!
> 
> 
> 
> I tried again and it still fails screenshot
> 
> 
> 
> Installed workbox, ran build, fails.
> 
> 
> 
> Installed workbox-window, ran build, fails.
> 
> 
> 
> hmm ... 

you can try removing workbox from package.json and run pnpm i again then try to build it

**Comment by jjaimealeman** [comment]
I have tried:

- with workbox without workbox-window
- without workbox with workbox-window

- with workbox with workbox-window
- without workbox without workbox-window

Build fails every time. :(

**Comment by zynth17** [comment]
> I have tried:
> 
> 
> 
> - with workbox without workbox-window
> 
> - without workbox with workbox-window
> 
> 
> 
> - with workbox with workbox-window
> 
> - without workbox without workbox-window
> 
> 
> 
> Build fails every time. :( 

can you provide me a link to repro?

**Comment by jjaimealeman** [comment]
> can you provide me a link to repro?

Sure, https://github.com/jjaimealeman/vitailse

**Comment by zynth17** [comment]
> > can you provide me a link to repro?
> 
> Sure, https://github.com/jjaimealeman/vitailse

cannot find your repro, please provide a new repro

**Comment by jjaimealeman** [comment]
> cannot find your repro, please provide a new repro
 
Apologize, it was private, now it's public. Go ahead 👍

**Comment by zynth17** [comment]
> > cannot find your repro, please provide a new repro
> 
> Apologize, it was private, now it's public. Go ahead 👍

this seems like the problem from the vite-pwa side. the workaround for is this only to install ```workbox-window``` first and remove it from the ```package.json``` without uninstalling the workbox-window from ```node_module``` folder

**Comment by zynth17** [comment]
> > > cannot find your repro, please provide a new repro
> > 
> > 
> > Apologize, it was private, now it's public. Go ahead 👍
> 
> this seems like the problem from the vite-pwa side. the workaround for is this only to install `workbox-window` first and remove it from the `package.json` without uninstalling the workbox-window from `node_module` folder

here check the issues, https://github.com/antfu/vite-plugin-pwa/issues/89
the only way to fix this is install workbox-window as devDependencies

**Pull request merged**
